spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cash_guard?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: hong  # 데이터베이스 사용자명
    password: '0427'  # 데이터베이스 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver
