spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/cash_guard
    username: hong  # 데이터베이스 사용자명
    password: '0427'  # 데이터베이스 비밀번호
    driver-class-name: org.mariadb.jdbc.Driver
    allow-multi-query: true

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ''
#    password: ''
#    properties:
#      mail:
#        debug: true
#        smtp:
#          auth: true
#          starttls:
#            enable: true
