spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/cash_guard
    username: hong
    password: ENC(D6E0WB3yvMBlKkMLxTNjjl6yDIuLFPpp4P/+UbtbcnzxtyWyxfdbzoJF2xZnsN9g)
    driver-class-name: org.mariadb.jdbc.Driver
    allow-multi-query: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: 'cashguard24@gmail.com'
    password: ENC(C/KJD1s0a5HvJUIuI8g57QTsrv7HjN5vcDvXUTXCaCqkXnMtmfFKtinuiNt6nHRvNtc/HRjfKmUji+6H1DamPg==)
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

hong:
  base-url: 'http://localhost:8084'

jasypt:
  encryptor:
    bean: cashGuardEncryptor
